#define TK_ARRAY_ASSIGN		1
#define TK_DOLLAR			2
#define TK_LPARAN			3
#define TK_RPARAN			4
#define TK_EQ				5
#define TK_MATCH			6
#define TK_ASSIGN			7
#define TK_NE				8
#define TK_NOMATCH			9
#define TK_EOL				10
#define TK_COMMA			11
#define TK_STRING			12
#define TK_APPEND			13
#define TK_PLUS				14
#define TK_LCURLY			15
#define TK_RCURLY			16
#define TK_LBRACKET			17
#define TK_RBRACKET			18
#define TK_SRVVARNAME		20
#define TK_INTEGER			21
#define TK_INCLUDE			22
#define TK_INCLUDE_SHELL	23
#define TK_GLOBAL			24
#define TK_ELSE				25
#define TK_LKEY				26